### ISSUE TITLE
Adapter only generates objects for degree of 4096

### ISSUE THREAD

**Issue by zaazad** [microsoft/SEAL-Embedded#2]
Do we need to manually change adapter to generate objects for n > 4096?

**Comment by WeiDaiWD** [comment]
Yes, when n > 4096, the memory consumption may be larger than 256 MB. If your device has a large RAM, you can manually increase it.

**Comment by WeiDaiWD** [comment]
Deepika has added support for degree larger than 4096. Please check the new version 1.1.0.

**Comment by zaazad** [comment]
Great, thank you so much!
