### ISSUE TITLE
data processing possibilities

### ISSUE THREAD

**Issue by Geordat** [microsoft/SEAL-Embedded#4]
Hello ! i want to do some processing to the data that i collected from the SEAL embedded lib but i have some issues . I manage to write a function that multiplies a plain text vector with an encrypted matrix .With degree of 8196 it works fine but with degree 4096 it outputs the wrong answer .Is there something that i can do to fix this ?  .I really want to use degree 4094 because the device is constrained

here is the code 

#include <iostream>
#include <iomanip>
#include <fstream>
#include <unistd.h>
#include "seal/seal.h"
#include "utils.h"

using namespace std;
using namespace seal;

Ciphertext mul_vec(Ciphertext mat,vector<double> mat1,EncryptionParameters params,int y,int x,int scale,GaloisKeys gal_keys){

    Ciphertext res;
    Plaintext pt;

    SEALContext context(params);
    Evaluator evaluator(context);
    CKKSEncoder encoder(context);

    vector<double> p(y*x);
    vector<Ciphertext> ctA_result(y);

    for(int i=0;i<y;i++){

          for(int ii=0;ii<y*x;ii++)
            p[ii] = 0.001 ;
        for(int ii=0;ii<x;ii++)
            p[ii] = mat1[i];
        
        evaluator.rotate_vector(mat,i*x, gal_keys,ctA_result[i]);
        encoder.encode(p,scale,pt);
        evaluator.multiply_plain(ctA_result[i],pt,ctA_result[i]);

    }
    evaluator.add_many(ctA_result,res);

    for(int i=0;i<y*x;i++)
                p[i] = 0.0001;

    for(int ii=0;ii<x;ii++)
            p[ii] =  1.0;
    return res;
}

int main(){

    
       //  size_t degree = 1024;
      // size_t degree = 2048;
      size_t degree = 4096;
     // size_t degree = 8192;
   //size_t degree = 16384;

    double scale = pow(2, 25);
    cout << "Parameters: degree " << degree << ", ntt_form, prime bit-lengths: {";
    switch (degree)
    {
        case 1024:
            cout << "27}, scale = pow(2, 20)" << endl;
            scale = pow(2, 20);
            break;
        case 2048:
            cout << "27, 27}, scale = pow(2, 25)" << endl;
            scale = pow(2, 25);
            break;
#ifdef SEALE_DEFAULT_4K_27BIT
        case 4096:
            cout << "27, 27, 27, 28}, scale = pow(2, 20)" << endl;
            scale = pow(2, 20);
            break;
#else
        case 4096:
            cout << "30, 30, 30, 19}, scale = pow(2, 25)" << endl;
            scale = pow(2, 25);
            break;
#endif
        case 8192:
            cout << "30 (x6), 38}, scale = pow(2, 25)" << endl;
            scale = pow(2, 25);
            break;
        case 16384:
            cout << "30 (x13), 48}, scale = pow(2, 25)" << endl;
            scale = pow(2, 25);
            break;
        // -- 32768 is technically possible, but we do not support it
        // case 32768: cout << "30 (x28), 41}, scale = pow(2, 25)" << endl;
        // scale = pow(2,25);
        // break;
        default: cout << "Please choose a valid degree." << endl; throw;
    }

    EncryptionParameters params(scheme_type::ckks);
    seal::SEALContext context = setup_seale_prime_default(degree, params);

    KeyGenerator keygen(context);
    Evaluator evaluator(context);
    CKKSEncoder encoder(context);
    
    SecretKey sk = keygen.secret_key();
    Decryptor decryptor(context, sk);
    PublicKey pk;
    GaloisKeys gal_keys;
    keygen.create_galois_keys(gal_keys);

    keygen.create_public_key(pk);
    Encryptor encryptor(context, pk);
    Ciphertext ct,ctB;
    Plaintext pt;

    int y = 2;
    int x = 4;
    vector<double> d = {0.7,0.7};

    vector<double> dw(12);
     

    vector<double> mat = {0.2  ,0.2 
                          ,0.2  ,0.2  
                          ,0.2 ,0.2,
                          0.2 ,0.2};

    encoder.encode(mat,scale,pt);
    encryptor.encrypt(pt,ct);
    cout<<"======="<<endl;
    Ciphertext cp = mul_vec(ct,d,params,y,x,scale,gal_keys);

    decryptor.decrypt(cp,pt);
    encoder.decode(pt,dw); 

    for(int i=0;i<3*4;i++)
        cout<<dw[i]<<"  "<<endl;
  
    return 0;
}

**Comment by WeiDaiWD** [comment]
The `scale` in `encoder.encode(mat,scale,pt)` can be smaller than `pow(2, 25)` and different from the one used for ciphertext. And the last prime which is chosen as 19-bit should be larger than the other primes. So maybe `{27, 27, 27, 27}` with scale `power(2, 20)` will work.
